import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import Providers from '@/components/providers'
import Header from '@/components/header'
import Footer from '@/components/footer'
import { cn } from '@/lib/utils'
import {Inter, Playfair_Display} from 'next/font/google'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}
const inter = Inter({subsets: ['latin'], variable: '--font-sans'})
const playfair = Playfair_Display({
  subsets:['latin'],
  variable: '--font-serif'//variable for using font
})
export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      {/* allows the body to grow to fit the screen */}
      <body className={cn('flex min-h-screen flex-col font-sans antialiased', inter.variable,playfair.variable)
       }>
      <Providers>
        <Header />
        <main className='grow'>{children}</main>
        <Footer />
      </Providers>
      </body>
    </html>
  )
}
